baseurl: /sanantonio
permalink: pretty
markdown: kramdown
paginate: 5
repo: sanantonio
github_org: maptime
maptime:
  chapter: MaptimeSATX
  twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
